### ISSUE TITLE
Here's another one for you...

### ISSUE THREAD

**Issue by Coldstorageunit** [tedder/miner_exporter#10]
```miner_exporter.py:safe_get_json:145:ERROR	error fetching https://testnet-api.helium.wtf/v1/accounts/1bv3FHW31PqGawWtQnb7YUcKcZaJcLq11rN1ctGquGPBmh5Aozs: HTTPSConnectionPool(host='testnet-api.helium.wtf', port=443): Max retries exceeded with url: /v1/accounts/1bv3FHW31PqGawWtQnb7YUcKcZaJcLq11rN1ctGquGPBmh5Aozs (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f434db2e040>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Traceback (most recent call last):
  File "/opt/app/miner_exporter.py", line 369, in <module>
    stats()
  File "<decorator-gen-1>", line 2, in stats
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "/opt/app/miner_exporter.py", line 132, in stats
    collect_balance(docker_container,miner_facts['address'],hotspot_name_str)
  File "/opt/app/miner_exporter.py", line 196, in collect_balance
    if not api_accounts.get('data') and not api_accounts['data'].get('balance'):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by tedder** [comment]
boolean logic fail. fixing right now.
