### ISSUE TITLE
crash getting balance from api 

### ISSUE THREAD

**Issue by gradoj** [tedder/miner_exporter#6]
```
miner_exporter    | miner_exporter.py:collect_miner_version:298:INFO    found miner version: 0.1.51
miner_exporter    | miner_exporter.py:collect_in_consensus:163:INFO    in consensus? 0 / false
miner_exporter    | Traceback (most recent call last):
miner_exporter    |   File "/opt/app/miner_exporter.py", line 307, in <module>
miner_exporter    |     stats()
miner_exporter    |   File "<decorator-gen-1>", line 2, in stats
miner_exporter    |   File "/usr/local/lib/python3.9/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
miner_exporter    |     return func(*args, **kwargs)
miner_exporter    |   File "/opt/app/miner_exporter.py", line 122, in stats
miner_exporter    |     collect_balance(docker_container,miner_facts['address'],hotspot_name_str)
miner_exporter    |   File "/opt/app/miner_exporter.py", line 132, in collect_balance
miner_exporter    |     owner = api_validators['data']['owner']
miner_exporter    | KeyError: 'data'
```
I'm assuming this is a new validator not yet showing up in api

**Comment by tedder** [comment]
fixed :) I still need to cache things.
