### ISSUE TITLE
exporter crashes with no docker container

### ISSUE THREAD

**Issue by gradoj** [tedder/miner_exporter#7]
Exporter crashes if you stop and remove validator docker container:
```
Traceback (most recent call last):
  File "/opt/app/miner_exporter.py", line 307, in <module>
    stats()
  File "<decorator-gen-1>", line 2, in stats
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "/opt/app/miner_exporter.py", line 106, in stats
    docker_container = dc.containers.get(VALIDATOR_CONTAINER_NAME)
  File "/usr/local/lib/python3.9/site-packages/docker/models/containers.py", line 889, in get
    resp = self.client.api.inspect_container(container_id)
  File "/usr/local/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/docker/api/container.py", line 773, in inspect_container
    return self._result(
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/validator/json: Not Found ("No such container: validator")

```

**Comment by tedder** [comment]
fixed! this was super-easy to test, duh.
