### ISSUE TITLE
Exporter Shut Down

### ISSUE THREAD

**Issue by Coldstorageunit** [tedder/miner_exporter#9]
Hey Tedder, 

Still seeing shutdowns on the miner_exporter, though far less frequently now. Restart works just fine. Typically will run for a couple days and then I'll see a shutdown. 

```miner_exporter.py:safe_get_json:139:ERROR	error fetching https://testnet-api.helium.wtf/v1/validators/1ZaCvhW663DFrchg3i5xvgXnH2en4QKc2BTTzPpMQLD7r7SQFci: HTTPSConnectionPool(host='testnet-api.helium.wtf', port=443): Max retries exceeded with url: /v1/validators/1ZaCvhW663DFrchg3i5xvgXnH2en4QKc2BTTzPpMQLD7r7SQFci (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f01762672b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):
  File "/opt/app/miner_exporter.py", line 327, in <module>
    stats()
  File "<decorator-gen-1>", line 2, in stats
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "/opt/app/miner_exporter.py", line 126, in stats
    collect_balance(docker_container,miner_facts['address'],hotspot_name_str)
  File "/opt/app/miner_exporter.py", line 149, in collect_balance
    if not api_validators.get('data') and not api_validators['data'].get('owner'):
AttributeError: 'NoneType' object has no attribute 'get'```

**Comment by tedder** [comment]
great! I'll get this one patched today.

**Comment by tedder** [comment]
fixed and added some logging too.
